name: generate-snake

on:
  schedule: # roda todo dia às 00h
    - cron: "0 0 * * *"
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Gerar cobrinha 🐍
        uses: Platane/snk@v3
        with:
          github_user_name: PLucasMendonca
          outputs: dist/snake.svg

      - name: Publicar no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
