# Substitua seu workflow atual por este (.github/workflows/snake.yml)
name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: PLucasMendonca
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
