name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: PLucasMendonca
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-s
